name: hive_universal_cache_example
description: Dart Project to contain examples for using hive_universal_cache.
version: 0.1.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  hive: ^2.0.5
  hive_universal_cache: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  hive_generator:
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
